services:
  timescaledb:
    image: timescale/timescaledb:2.18.1-pg17 # This is the lightweight version using Alpine
    environment:
      POSTGRES_DB: postgres # This is the default, but being explicit here.
      POSTGRES_USER: postgres # Also default, also being explicit.
      POSTGRES_PASSWORD: secret
    ports:
      - 5469:5432 # Exposing 5469 for development. Should remove in production.
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
