services:
  vector-shipper:
    image: timberio/vector:0.45.0-debian
    container_name: vector-shipper
    volumes:
      - ./logs:/logs
      - ./vector-shipper.yaml:/etc/vector/vector.yaml:ro
    command: ["-c", "/etc/vector/vector.yaml"]
    networks:
      - unilogs-network

networks:
  unilogs-network:
    external: true