services:
  vector-shipper:
    image: timberio/vector:0.45.0-debian
    container_name: vector-shipper-${DOCKER_CONTAINER_NAME}
    volumes:
      - ./logs:/logs
      - ./vector-shipper.yaml:/etc/vector/vector.yaml:ro
      - ./apache-remap.vrl:/apache-remap.vrl:ro
    command: ["-c", "/etc/vector/vector.yaml"]