[INPUT]
    Name          tail
    Path          /Users/davidpark/Desktop/logingestion/logger/logs/app.log
    Parser        json
    Tag           app_logs
    DB            /tmp/fluentbit.db   # To store the state of the last processed line, required for tailing logs.

[OUTPUT]
    Name          http
    Match         app_logs
    Host          127.0.0.1
    Port          8080
    URI           /logs
    Format        json
    Header        Content-Type application/json
    Retry_Limit   false

