[SERVICE]
  Parsers_File    parsers.conf

[INPUT]
    Name          tail
    Path          /logger/logs/app.log
    Parser        apache
    Tag           app_logs
    DB            /tmp/fluentbit.db

[OUTPUT]
    Name          loki
    Match         app*logs
    Host          127.0.0.1 
    Port          3100